volumes:
  everstone_db:


services:
  everstone:
    container_name: everstone-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      - DATABASE_URL=file:./db/prod.db
      - BTCPAY_URL=${BTCPAY_URL}
      - BTCPAY_API_KEY=${BTCPAY_API_KEY}
      - BTCPAY_STORE_ID=${BTCPAY_STORE_ID}
    volumes:
      # Use a named volume for better permission management
      - everstone_db:/app/prisma/db

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: everstone-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - everstone
